# Generated by Django 3.0.5 on 2020-05-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
                ('amount', models.CharField(max_length=9)),
                ('currency', models.CharField(max_length=5)),
                ('mail_sent', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
