# Generated by Django 3.0.6 on 2020-05-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_zoom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donation_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
